set(CSP_TESTS_SOURCE_DIR  ${CMAKE_CURRENT_SOURCE_DIR}/Tests/src)

set(CSP_TESTS_SOURCES
    ${CSP_TESTS_SOURCE_DIR}/Awaitable.h
    ${CSP_TESTS_SOURCE_DIR}/Main.cpp
    ${CSP_TESTS_SOURCE_DIR}/MultiplayerTestRunnerProcess.cpp
    ${CSP_TESTS_SOURCE_DIR}/MultiplayerTestRunnerProcess.h
    ${CSP_TESTS_SOURCE_DIR}/PublicTestBase.cpp
    ${CSP_TESTS_SOURCE_DIR}/PublicTestBase.h
    ${CSP_TESTS_SOURCE_DIR}/RAIIMockLogger.h
    ${CSP_TESTS_SOURCE_DIR}/TestHelpers.cpp
    ${CSP_TESTS_SOURCE_DIR}/TestHelpers.h

    ${CSP_TESTS_SOURCE_DIR}/InternalTests/ComponentSchemaScriptBindingTests.cpp
    ${CSP_TESTS_SOURCE_DIR}/InternalTests/EncodeTests.cpp
    ${CSP_TESTS_SOURCE_DIR}/InternalTests/EntityPropertyTests.cpp
    ${CSP_TESTS_SOURCE_DIR}/InternalTests/EventTests.cpp
    ${CSP_TESTS_SOURCE_DIR}/InternalTests/FeatureFlagTests.cpp
    ${CSP_TESTS_SOURCE_DIR}/InternalTests/HashTests.cpp
    ${CSP_TESTS_SOURCE_DIR}/InternalTests/JsonTests.cpp
    ${CSP_TESTS_SOURCE_DIR}/InternalTests/MaterialUnitTests.cpp
    ${CSP_TESTS_SOURCE_DIR}/InternalTests/MCSTests.cpp
    ${CSP_TESTS_SOURCE_DIR}/InternalTests/NetworkEventSerialisationTests.cpp
    ${CSP_TESTS_SOURCE_DIR}/InternalTests/NewFeatureTests.cpp
    ${CSP_TESTS_SOURCE_DIR}/InternalTests/PlatformTestUtils.cpp
    ${CSP_TESTS_SOURCE_DIR}/InternalTests/PlatformTestUtils.h
    ${CSP_TESTS_SOURCE_DIR}/InternalTests/SceneDescriptionTests.cpp
    ${CSP_TESTS_SOURCE_DIR}/InternalTests/SchedulerTests.cpp
    ${CSP_TESTS_SOURCE_DIR}/InternalTests/ServicesTests.cpp
    ${CSP_TESTS_SOURCE_DIR}/InternalTests/SignalRSerializerTests.cpp
    ${CSP_TESTS_SOURCE_DIR}/InternalTests/SpaceEntityTests.cpp
    ${CSP_TESTS_SOURCE_DIR}/InternalTests/SpaceHelperTests.cpp
    ${CSP_TESTS_SOURCE_DIR}/InternalTests/UniqueStringTest.cpp
    ${CSP_TESTS_SOURCE_DIR}/InternalTests/WebClientTests.cpp
    ${CSP_TESTS_SOURCE_DIR}/InternalTests/WebSocketClientTests.cpp
    ${CSP_TESTS_SOURCE_DIR}/InternalTests/XMLTestResultWriter.cpp
    ${CSP_TESTS_SOURCE_DIR}/InternalTests/XMLTestResultWriter.h

    ${CSP_TESTS_SOURCE_DIR}/InternalTests/CommonTypeTests/Array.cpp
    ${CSP_TESTS_SOURCE_DIR}/InternalTests/CommonTypeTests/List.cpp
    ${CSP_TESTS_SOURCE_DIR}/InternalTests/CommonTypeTests/Map.cpp
    ${CSP_TESTS_SOURCE_DIR}/InternalTests/CommonTypeTests/Optional.cpp
    ${CSP_TESTS_SOURCE_DIR}/InternalTests/CommonTypeTests/String.cpp
    ${CSP_TESTS_SOURCE_DIR}/InternalTests/CommonTypeTests/StringFormat.cpp
    ${CSP_TESTS_SOURCE_DIR}/InternalTests/CommonTypeTests/Vector2.cpp
    ${CSP_TESTS_SOURCE_DIR}/InternalTests/CommonTypeTests/Vector3.cpp
    ${CSP_TESTS_SOURCE_DIR}/InternalTests/CommonTypeTests/Vector4.cpp

    ${CSP_TESTS_SOURCE_DIR}/Mocks/SignalRConnectionMock.h
    ${CSP_TESTS_SOURCE_DIR}/Mocks/WebClientMock.h

    ${CSP_TESTS_SOURCE_DIR}/PublicAPITests/AnalyticsSystemTests.cpp
    ${CSP_TESTS_SOURCE_DIR}/PublicAPITests/AnchorSystemTests.cpp
    ${CSP_TESTS_SOURCE_DIR}/PublicAPITests/ApplicationSettingsSystemTests.cpp
    ${CSP_TESTS_SOURCE_DIR}/PublicAPITests/AssetSystemTestHelpers.h
    ${CSP_TESTS_SOURCE_DIR}/PublicAPITests/AssetSystemTests.cpp
    ${CSP_TESTS_SOURCE_DIR}/PublicAPITests/CancellationTokenTests.cpp
    ${CSP_TESTS_SOURCE_DIR}/PublicAPITests/ConversationSystemTests.cpp
    ${CSP_TESTS_SOURCE_DIR}/PublicAPITests/DateTimeTests.cpp
    ${CSP_TESTS_SOURCE_DIR}/PublicAPITests/ECommerceSystemTests.cpp
    ${CSP_TESTS_SOURCE_DIR}/PublicAPITests/EventBusTests.cpp
    ${CSP_TESTS_SOURCE_DIR}/PublicAPITests/EventTicketingSystemTests.cpp
    ${CSP_TESTS_SOURCE_DIR}/PublicAPITests/ExternalServicesTests.cpp
    ${CSP_TESTS_SOURCE_DIR}/PublicAPITests/GeneralContinuationsTests.cpp
    ${CSP_TESTS_SOURCE_DIR}/PublicAPITests/GraphQLSystemTests.cpp
    ${CSP_TESTS_SOURCE_DIR}/PublicAPITests/HotspotSequenceTests.cpp
    ${CSP_TESTS_SOURCE_DIR}/PublicAPITests/LeaderElectionTests.cpp
    ${CSP_TESTS_SOURCE_DIR}/PublicAPITests/LODTests.cpp
    ${CSP_TESTS_SOURCE_DIR}/PublicAPITests/LogSystemTests.cpp
    ${CSP_TESTS_SOURCE_DIR}/PublicAPITests/MaintenanceSystemTests.cpp
    ${CSP_TESTS_SOURCE_DIR}/PublicAPITests/MaterialTests.cpp
    ${CSP_TESTS_SOURCE_DIR}/PublicAPITests/MCSExternalDependencyTests.cpp
    ${CSP_TESTS_SOURCE_DIR}/PublicAPITests/MimeTypeHelperTests.cpp
    ${CSP_TESTS_SOURCE_DIR}/PublicAPITests/MultiplayerSystemTests.cpp
    ${CSP_TESTS_SOURCE_DIR}/PublicAPITests/MultiplayerTestRunnerProcessTests.cpp
    ${CSP_TESTS_SOURCE_DIR}/PublicAPITests/MultiPlayerTests.cpp
    ${CSP_TESTS_SOURCE_DIR}/PublicAPITests/OfflineRealtimeEngineTests.cpp
    ${CSP_TESTS_SOURCE_DIR}/PublicAPITests/OnlineRealtimeEngineTests.cpp
    ${CSP_TESTS_SOURCE_DIR}/PublicAPITests/PointOfInterestSystemTests.cpp
    ${CSP_TESTS_SOURCE_DIR}/PublicAPITests/QuotaSystemTests.cpp
    ${CSP_TESTS_SOURCE_DIR}/PublicAPITests/RealtimeEngineEntityTests.cpp
    ${CSP_TESTS_SOURCE_DIR}/PublicAPITests/ReplicatedValueTests.cpp
    ${CSP_TESTS_SOURCE_DIR}/PublicAPITests/ScriptSystemTests.cpp
    ${CSP_TESTS_SOURCE_DIR}/PublicAPITests/SequenceSystemTests.cpp
    ${CSP_TESTS_SOURCE_DIR}/PublicAPITests/SettingsSystemTests.cpp
    ${CSP_TESTS_SOURCE_DIR}/PublicAPITests/SpaceSystemTestHelpers.h
    ${CSP_TESTS_SOURCE_DIR}/PublicAPITests/SpaceSystemTests.cpp
    ${CSP_TESTS_SOURCE_DIR}/PublicAPITests/SpaceTransformTests.cpp
    ${CSP_TESTS_SOURCE_DIR}/PublicAPITests/SystemResultTests.cpp
    ${CSP_TESTS_SOURCE_DIR}/PublicAPITests/UserSystemTestHelpers.h
    ${CSP_TESTS_SOURCE_DIR}/PublicAPITests/UserSystemTests.cpp
    ${CSP_TESTS_SOURCE_DIR}/PublicAPITests/VectorTests.cpp

    ${CSP_TESTS_SOURCE_DIR}/PublicAPITests/ComponentTests/AIChatbotComponentTests.cpp
    ${CSP_TESTS_SOURCE_DIR}/PublicAPITests/ComponentTests/AnimatedModelComponentTests.cpp
    ${CSP_TESTS_SOURCE_DIR}/PublicAPITests/ComponentTests/AudioComponentTests.cpp
    ${CSP_TESTS_SOURCE_DIR}/PublicAPITests/ComponentTests/AvatarComponentTests.cpp
    ${CSP_TESTS_SOURCE_DIR}/PublicAPITests/ComponentTests/CinematicCameraComponentTests.cpp
    ${CSP_TESTS_SOURCE_DIR}/PublicAPITests/ComponentTests/CollisionComponentTests.cpp
    ${CSP_TESTS_SOURCE_DIR}/PublicAPITests/ComponentTests/ComponentTests.cpp
    ${CSP_TESTS_SOURCE_DIR}/PublicAPITests/ComponentTests/ConversationComponentTests.cpp
    ${CSP_TESTS_SOURCE_DIR}/PublicAPITests/ComponentTests/CustomComponentTests.cpp
    ${CSP_TESTS_SOURCE_DIR}/PublicAPITests/ComponentTests/ECommerceComponentTests.cpp
    ${CSP_TESTS_SOURCE_DIR}/PublicAPITests/ComponentTests/FiducialMarkerComponentTests.cpp
    ${CSP_TESTS_SOURCE_DIR}/PublicAPITests/ComponentTests/FogComponentTests.cpp
    ${CSP_TESTS_SOURCE_DIR}/PublicAPITests/ComponentTests/GaussianSplatComponentTests.cpp
    ${CSP_TESTS_SOURCE_DIR}/PublicAPITests/ComponentTests/HotspotComponentTests.cpp
    ${CSP_TESTS_SOURCE_DIR}/PublicAPITests/ComponentTests/ImageComponentTests.cpp
    ${CSP_TESTS_SOURCE_DIR}/PublicAPITests/ComponentTests/LightComponentTests.cpp
    ${CSP_TESTS_SOURCE_DIR}/PublicAPITests/ComponentTests/LinkComponentTests.cpp
    ${CSP_TESTS_SOURCE_DIR}/PublicAPITests/ComponentTests/PortalComponentTests.cpp
    ${CSP_TESTS_SOURCE_DIR}/PublicAPITests/ComponentTests/ReflectionComponentTests.cpp
    ${CSP_TESTS_SOURCE_DIR}/PublicAPITests/ComponentTests/ScreenSharingComponentTests.cpp
    ${CSP_TESTS_SOURCE_DIR}/PublicAPITests/ComponentTests/SplineComponentTests.cpp
    ${CSP_TESTS_SOURCE_DIR}/PublicAPITests/ComponentTests/StaticModelComponentTests.cpp
    ${CSP_TESTS_SOURCE_DIR}/PublicAPITests/ComponentTests/TextComponentTests.cpp
    ${CSP_TESTS_SOURCE_DIR}/PublicAPITests/ComponentTests/VideoPlayerComponentTests.cpp
)