// WARNING: DO NOT EDIT THIS FILE! IT IS A GENERATED FILE AND
//   ANY CHANGES YOU MAKE WILL BE OVERWRITTEN ON THE NEXT BUILD

#nullable enable annotations

using System;
using System.Collections.Generic;
using System.Reflection;
using System.Runtime.InteropServices;
using System.Security;
using System.Threading.Tasks;

namespace Csp.Systems
{
    /// <summary>A JavaScript based scripting system that can be used to create advanced behaviours and interactions between entities in spaces.</summary>

    public class ScriptSystem : NativeClassWrapper
    {
        internal override string _safeTypeName { get; } = "csp_systems_ScriptSystem";

        #region P/Invoke
#pragma warning disable IDE1006



        [
            DllImport(
#if !UNITY_EDITOR && UNITY_IOS
            "__Internal"
#elif DEBUG && !UNITY_EDITOR_OSX && !UNITY_STANDALONE_OSX
                "ConnectedSpacesPlatform_D"
#else
                "ConnectedSpacesPlatform"
#endif
            ),
            SuppressUnmanagedCodeSecurity
        ]
        static extern void csp_systems_ScriptSystem_Dtor(IntPtr @class);

        [
            DllImport(
#if !UNITY_EDITOR && UNITY_IOS
            "__Internal"
#elif DEBUG && !UNITY_EDITOR_OSX && !UNITY_STANDALONE_OSX
                "ConnectedSpacesPlatform_D"
#else
                "ConnectedSpacesPlatform"
#endif
            ),
            SuppressUnmanagedCodeSecurity
        ]
        static extern void csp_systems_ScriptSystem_Initialise_void(IntPtr @class);

        [
            DllImport(
#if !UNITY_EDITOR && UNITY_IOS
            "__Internal"
#elif DEBUG && !UNITY_EDITOR_OSX && !UNITY_STANDALONE_OSX
                "ConnectedSpacesPlatform_D"
#else
                "ConnectedSpacesPlatform"
#endif
            ),
            SuppressUnmanagedCodeSecurity
        ]
        static extern void csp_systems_ScriptSystem_Shutdown_void(IntPtr @class);

        [
            DllImport(
#if !UNITY_EDITOR && UNITY_IOS
            "__Internal"
#elif DEBUG && !UNITY_EDITOR_OSX && !UNITY_STANDALONE_OSX
                "ConnectedSpacesPlatform_D"
#else
                "ConnectedSpacesPlatform"
#endif
            ),
            SuppressUnmanagedCodeSecurity
        ]
        static extern bool csp_systems_ScriptSystem_RunScript_bool_int64_t_StringRC(
            IntPtr @class,
            long ContextId,
            IntPtr ScriptText
        );

        [
            DllImport(
#if !UNITY_EDITOR && UNITY_IOS
            "__Internal"
#elif DEBUG && !UNITY_EDITOR_OSX && !UNITY_STANDALONE_OSX
                "ConnectedSpacesPlatform_D"
#else
                "ConnectedSpacesPlatform"
#endif
            ),
            SuppressUnmanagedCodeSecurity
        ]
        static extern bool csp_systems_ScriptSystem_RunScriptFile_bool_int64_t_StringRC(
            IntPtr @class,
            long ContextId,
            IntPtr ScriptFilePath
        );

        [
            DllImport(
#if !UNITY_EDITOR && UNITY_IOS
            "__Internal"
#elif DEBUG && !UNITY_EDITOR_OSX && !UNITY_STANDALONE_OSX
                "ConnectedSpacesPlatform_D"
#else
                "ConnectedSpacesPlatform"
#endif
            ),
            SuppressUnmanagedCodeSecurity
        ]
        static extern NativePointer csp_systems_ScriptSystem_Ctor();

#pragma warning restore IDE1006
        #endregion

        internal ScriptSystem(NativePointer ptr) : base(ptr) { }

        ~ScriptSystem()
        {
            //RealDispose();
        }

        void RealDispose()
        {
            if (_ownsPtr && !_disposed)
            {
                csp_systems_ScriptSystem_Dtor(_ptr);
                _disposed = true;
            }

            _disposed = true;
        }

        public void Dispose()
        {
            RealDispose();
            GC.SuppressFinalize(this);
        }

        /// <summary>Starts up the JavaScript runtime context.</summary>


        public void Initialise()
        {
            csp_systems_ScriptSystem_Initialise_void(_ptr);
        }

        /// <summary>Shuts down and deletes the JavaScript runtime context.</summary>


        public void Shutdown()
        {
            csp_systems_ScriptSystem_Shutdown_void(_ptr);
        }

        /// <summary>Attempts to execute a script in a given context.</summary>
        /// <param name="ContextId">The context in which to run the script. If the provided context does not exist, the script run will fail.</param>
        /// <param name="ScriptText">The script to execute.</param>
        /// <returns>A boolean representing success running the script.</returns>


        public bool RunScript(long ContextId, string ScriptText)
        {
            var _result = csp_systems_ScriptSystem_RunScript_bool_int64_t_StringRC(
                _ptr,
                ContextId,
                WrapperHelper.StringToNativeUTF8(ScriptText)
            );

            return _result;
        }

        /// <summary>Attempts to execute a script from a given file path in the given context.</summary>
        /// <param name="ContextId">The context in which to run the script. If the provided context does not exist, the script run will fail.</param>
        /// <param name="ScriptFilePath">The file path of the script to execute.</param>
        /// <returns>A boolean representing success running the script.</returns>


        public bool RunScriptFile(long ContextId, string ScriptFilePath)
        {
            var _result = csp_systems_ScriptSystem_RunScriptFile_bool_int64_t_StringRC(
                _ptr,
                ContextId,
                WrapperHelper.StringToNativeUTF8(ScriptFilePath)
            );

            return _result;
        }

        protected ScriptSystem() { }
    }
}

