#pragma once

#include "Olympus/Multiplayer/ComponentBase.h"

namespace oly_multiplayer
{
enum class SplinePropertyKeys
{
    Waypoints = 0,
    Num

};
/**
 * @ingroup SplineSpaceComponent
 * @brief Data representation of a SplineSpaceComponent.
 *
 * SplineSpaceComponent allows for the calculation of Cubic splines and a point along the position of that spline.
 */
class OLY_API SplineSpaceComponent : public ComponentBase
{
public:
    SplineSpaceComponent(SpaceEntity* Parent);

    /// @brief Generate a vector3 at a chosen position along the spline
    /// Note: Generates a cubic spline position from current Waypoints
    /// @param NormalisedDistance float : Distance along the spline being evaluated between a value of 0 and 1
    /// @return position value of X,Y,Z in Vector3 format of the generated spline position
    oly_common::Vector3 GetLocationAlongSpline(float NormalisedDistance);

    /// @brief Get waypoints used to generate spline
    /// Note: Get the number of positions generated by the spline
    /// @return Current waypoint Values Set
    oly_common::List<oly_common::Vector3> GetWaypoints() const;

    /// @brief Set waypoints to generate the spline
    /// Note: Set the number of positions generated by the spline
    /// @param Value oly_common::List<oly_common::Vector3> : number of positions between each waypoint
    void SetWaypoints(const oly_common::List<oly_common::Vector3>& Waypoints);
};
} // namespace oly_multiplayer
