// WARNING: DO NOT EDIT THIS FILE! IT IS A GENERATED FILE AND
//   ANY CHANGES YOU MAKE WILL BE OVERWRITTEN ON THE NEXT BUILD

#nullable enable annotations

using System;
using System.Collections.Generic;
using System.Reflection;
using System.Runtime.InteropServices;
using System.Security;
using System.Threading.Tasks;

namespace Csp.Multiplayer
{
    /// <summary>Enum used to specify the type of a conversation system network event.</summary>

    public enum ConversationMessageType
    {
        NewMessage,
        DeleteMessage,
        DeleteConversation,
        ConversationInformation,
        MessageInformation,
    }
}

