// WARNING: DO NOT EDIT THIS FILE! IT IS A GENERATED FILE AND
//   ANY CHANGES YOU MAKE WILL BE OVERWRITTEN ON THE NEXT BUILD

#nullable enable annotations

using System;
using System.Collections.Generic;
using System.Reflection;
using System.Runtime.InteropServices;
using System.Security;
using System.Threading.Tasks;

namespace Csp.Systems
{
    /// @ingroup Space System
    /// <summary>Data class used to contain information when attempting to get an array of spaces.</summary>

    public class BasicSpacesResult : Csp.Systems.ResultBase, IDisposable
    {
        internal override string _safeTypeName { get; } = "csp_systems_BasicSpacesResult";

        #region P/Invoke
#pragma warning disable IDE1006



        [
            DllImport(
#if !UNITY_EDITOR && UNITY_IOS
            "__Internal"
#elif DEBUG && !UNITY_EDITOR_OSX && !UNITY_STANDALONE_OSX
                "ConnectedSpacesPlatform_D"
#else
                "ConnectedSpacesPlatform"
#endif
            ),
            SuppressUnmanagedCodeSecurity
        ]
        static extern NativePointer csp_systems_BasicSpacesResult_GetSpaces_ArrayR(IntPtr @class);

        [
            DllImport(
#if !UNITY_EDITOR && UNITY_IOS
            "__Internal"
#elif DEBUG && !UNITY_EDITOR_OSX && !UNITY_STANDALONE_OSX
                "ConnectedSpacesPlatform_D"
#else
                "ConnectedSpacesPlatform"
#endif
            ),
            SuppressUnmanagedCodeSecurity
        ]
        static extern ulong csp_systems_BasicSpacesResult_GetTotalCountC_uint64_t(IntPtr @class);

        [
            DllImport(
#if !UNITY_EDITOR && UNITY_IOS
            "__Internal"
#elif DEBUG && !UNITY_EDITOR_OSX && !UNITY_STANDALONE_OSX
                "ConnectedSpacesPlatform_D"
#else
                "ConnectedSpacesPlatform"
#endif
            ),
            SuppressUnmanagedCodeSecurity
        ]
        static extern NativePointer csp_systems_BasicSpacesResult_Ctor_voidP(IntPtr arg1);

        [
            DllImport(
#if !UNITY_EDITOR && UNITY_IOS
            "__Internal"
#elif DEBUG && !UNITY_EDITOR_OSX && !UNITY_STANDALONE_OSX
                "ConnectedSpacesPlatform_D"
#else
                "ConnectedSpacesPlatform"
#endif
            ),
            SuppressUnmanagedCodeSecurity
        ]
        static extern void csp_systems_BasicSpacesResult_Dtor(IntPtr @class);

#pragma warning restore IDE1006
        #endregion

        internal BasicSpacesResult(NativePointer ptr) : base(ptr) { }

        public BasicSpacesResult(Csp.Systems.ResultBase baseInstance)
            : base(new NativePointer(baseInstance._ptr, baseInstance._ownsPtr ? (byte)1 : (byte)0))
        {
            // Prevent previous instance from freeing underlying pointer when destroyed
            baseInstance._ownsPtr = false;
        }

        /// <summary>Retrieves the spaces array being stored.</summary>
        /// <returns>Pointer to spaces array</returns>


        public Csp.Common.Array<Csp.Systems.BasicSpace> GetSpaces()
        {
            var _result = new Csp.Common.Array<Csp.Systems.BasicSpace>(
                csp_systems_BasicSpacesResult_GetSpaces_ArrayR(_ptr)
            );

            return _result;
        }

        /// <summary>Retrieves the async operation total number of result spaces.</summary>
        /// <remarks>If the async operation was using pagination this count number represents the sum of space sizes from every page.</remarks>
        /// <remarks>If the async operation is not using pagination this count number will be equal to the spaces array size.</remarks>
        /// <returns>Count number as described above</returns>


        public ulong GetTotalCount()
        {
            var _result = csp_systems_BasicSpacesResult_GetTotalCountC_uint64_t(_ptr);

            return _result;
        }

        ~BasicSpacesResult()
        {
            //RealDispose();
        }

        void RealDispose()
        {
            if (_ownsPtr && !_disposed)
            {
                csp_systems_BasicSpacesResult_Dtor(_ptr);
                _disposed = true;
            }

            _disposed = true;
        }

        new public void Dispose()
        {
            RealDispose();
            GC.SuppressFinalize(this);
        }
    }
}

