// WARNING: DO NOT EDIT THIS FILE! IT IS A GENERATED FILE AND
//   ANY CHANGES YOU MAKE WILL BE OVERWRITTEN ON THE NEXT BUILD

#nullable enable annotations

using System;
using System.Collections.Generic;
using System.Reflection;
using System.Runtime.InteropServices;
using System.Security;
using System.Threading.Tasks;

namespace Csp.Systems
{
    /// @ingroup Space System
    /// <summary>Data representation of roles for a group of invited users, the email link and the destination link to be included in the invite emails</summary>

    public class InviteUserRoleInfoCollection : NativeClassWrapper, IDisposable
    {
        internal override string _safeTypeName { get; } = "csp_systems_InviteUserRoleInfoCollection";

        #region P/Invoke
#pragma warning disable IDE1006


        [
            DllImport(
#if !UNITY_EDITOR && UNITY_IOS
            "__Internal"
#elif DEBUG && !UNITY_EDITOR_OSX && !UNITY_STANDALONE_OSX
                "ConnectedSpacesPlatform_D"
#else
                "ConnectedSpacesPlatform"
#endif
            ),
            SuppressUnmanagedCodeSecurity
        ]
        static extern IntPtr csp_systems_InviteUserRoleInfoCollection__Get_EmailLinkUrl(IntPtr @class);

        [
            DllImport(
#if !UNITY_EDITOR && UNITY_IOS
            "__Internal"
#elif DEBUG && !UNITY_EDITOR_OSX && !UNITY_STANDALONE_OSX
                "ConnectedSpacesPlatform_D"
#else
                "ConnectedSpacesPlatform"
#endif
            ),
            SuppressUnmanagedCodeSecurity
        ]
        static extern void csp_systems_InviteUserRoleInfoCollection__Set_EmailLinkUrl(IntPtr @class, IntPtr value);

        [
            DllImport(
#if !UNITY_EDITOR && UNITY_IOS
            "__Internal"
#elif DEBUG && !UNITY_EDITOR_OSX && !UNITY_STANDALONE_OSX
                "ConnectedSpacesPlatform_D"
#else
                "ConnectedSpacesPlatform"
#endif
            ),
            SuppressUnmanagedCodeSecurity
        ]
        static extern IntPtr csp_systems_InviteUserRoleInfoCollection__Get_SignupUrl(IntPtr @class);

        [
            DllImport(
#if !UNITY_EDITOR && UNITY_IOS
            "__Internal"
#elif DEBUG && !UNITY_EDITOR_OSX && !UNITY_STANDALONE_OSX
                "ConnectedSpacesPlatform_D"
#else
                "ConnectedSpacesPlatform"
#endif
            ),
            SuppressUnmanagedCodeSecurity
        ]
        static extern void csp_systems_InviteUserRoleInfoCollection__Set_SignupUrl(IntPtr @class, IntPtr value);

        [
            DllImport(
#if !UNITY_EDITOR && UNITY_IOS
            "__Internal"
#elif DEBUG && !UNITY_EDITOR_OSX && !UNITY_STANDALONE_OSX
                "ConnectedSpacesPlatform_D"
#else
                "ConnectedSpacesPlatform"
#endif
            ),
            SuppressUnmanagedCodeSecurity
        ]
        static extern NativePointer csp_systems_InviteUserRoleInfoCollection__Get_InviteUserRoleInfos(IntPtr @class);

        [
            DllImport(
#if !UNITY_EDITOR && UNITY_IOS
            "__Internal"
#elif DEBUG && !UNITY_EDITOR_OSX && !UNITY_STANDALONE_OSX
                "ConnectedSpacesPlatform_D"
#else
                "ConnectedSpacesPlatform"
#endif
            ),
            SuppressUnmanagedCodeSecurity
        ]
        static extern void csp_systems_InviteUserRoleInfoCollection__Set_InviteUserRoleInfos(
            IntPtr @class,
            IntPtr value
        );

        [
            DllImport(
#if !UNITY_EDITOR && UNITY_IOS
            "__Internal"
#elif DEBUG && !UNITY_EDITOR_OSX && !UNITY_STANDALONE_OSX
                "ConnectedSpacesPlatform_D"
#else
                "ConnectedSpacesPlatform"
#endif
            ),
            SuppressUnmanagedCodeSecurity
        ]
        static extern NativePointer csp_systems_InviteUserRoleInfoCollection_Ctor();

        [
            DllImport(
#if !UNITY_EDITOR && UNITY_IOS
            "__Internal"
#elif DEBUG && !UNITY_EDITOR_OSX && !UNITY_STANDALONE_OSX
                "ConnectedSpacesPlatform_D"
#else
                "ConnectedSpacesPlatform"
#endif
            ),
            SuppressUnmanagedCodeSecurity
        ]
        static extern NativePointer csp_systems_InviteUserRoleInfoCollection_Ctor_InviteUserRoleInfoCollectionRC(
            IntPtr Other
        );

        [
            DllImport(
#if !UNITY_EDITOR && UNITY_IOS
            "__Internal"
#elif DEBUG && !UNITY_EDITOR_OSX && !UNITY_STANDALONE_OSX
                "ConnectedSpacesPlatform_D"
#else
                "ConnectedSpacesPlatform"
#endif
            ),
            SuppressUnmanagedCodeSecurity
        ]
        static extern void csp_systems_InviteUserRoleInfoCollection_Dtor(IntPtr @class);

#pragma warning restore IDE1006
        #endregion

        internal InviteUserRoleInfoCollection(NativePointer ptr) : base(ptr) { }

        public string EmailLinkUrl
        {
            get => WrapperHelper.NativeUTF8ToString(csp_systems_InviteUserRoleInfoCollection__Get_EmailLinkUrl(_ptr));
            set =>
                csp_systems_InviteUserRoleInfoCollection__Set_EmailLinkUrl(
                    _ptr,
                    WrapperHelper.StringToNativeUTF8(value)
                );
        }

        public string SignupUrl
        {
            get => WrapperHelper.NativeUTF8ToString(csp_systems_InviteUserRoleInfoCollection__Get_SignupUrl(_ptr));
            set =>
                csp_systems_InviteUserRoleInfoCollection__Set_SignupUrl(_ptr, WrapperHelper.StringToNativeUTF8(value));
        }

        public Csp.Common.Array<Csp.Systems.InviteUserRoleInfo> InviteUserRoleInfos
        {
            get =>
                new Csp.Common.Array<Csp.Systems.InviteUserRoleInfo>(
                    csp_systems_InviteUserRoleInfoCollection__Get_InviteUserRoleInfos(_ptr)
                );
            set => csp_systems_InviteUserRoleInfoCollection__Set_InviteUserRoleInfos(_ptr, value._ptr);
        }

        public InviteUserRoleInfoCollection()
        {
            var np = csp_systems_InviteUserRoleInfoCollection_Ctor();
            _ptr = np.Pointer;
            _ownsPtr = np.OwnsOwnData;
        }

        public InviteUserRoleInfoCollection(Csp.Systems.InviteUserRoleInfoCollection Other)
        {
            var np = csp_systems_InviteUserRoleInfoCollection_Ctor_InviteUserRoleInfoCollectionRC(Other._ptr);
            _ptr = np.Pointer;
            _ownsPtr = np.OwnsOwnData;
        }

        ~InviteUserRoleInfoCollection()
        {
            //RealDispose();
        }

        void RealDispose()
        {
            if (_ownsPtr && !_disposed)
            {
                csp_systems_InviteUserRoleInfoCollection_Dtor(_ptr);
                _disposed = true;
            }

            _disposed = true;
        }

        public void Dispose()
        {
            RealDispose();
            GC.SuppressFinalize(this);
        }
    }
}

