// WARNING: DO NOT EDIT THIS FILE! IT IS A GENERATED FILE AND
//   ANY CHANGES YOU MAKE WILL BE OVERWRITTEN ON THE NEXT BUILD

#nullable enable annotations

using System;
using System.Collections.Generic;
using System.Reflection;
using System.Runtime.InteropServices;
using System.Security;
using System.Threading.Tasks;

namespace Csp.Multiplayer
{
    /// <summary>This Enum should be used to determine what kind of operation the component update represents.</summary>
    /// <remarks>Update means properties on the component have updated, all need to be checked as we do not provide reference of specific property updates.</remarks>
    /// <remarks>Add means the component is newly added, clients should ensure that this triggers appropriate instantiation of wrapping objects.</remarks>
    /// <remarks>All properties for the component should be included.</remarks>
    /// <remarks>Delete means the component has been marked for deletion. It is likely that some other clients will not have the component at the point this is</remarks>
    /// <remarks>recieved. Any wrapping data objects should be deleted when this is recieved, and clients should cease updating this component as any call would</remarks>
    /// <remarks>fail. The CSP representation of the component has been removed at this point.</remarks>

    public enum ComponentUpdateType
    {
        Update,
        Add,
        Delete,
    }
}

