// WARNING: DO NOT EDIT THIS FILE! IT IS A GENERATED FILE AND
//   ANY CHANGES YOU MAKE WILL BE OVERWRITTEN ON THE NEXT BUILD

#nullable enable annotations

using System;
using System.Collections.Generic;
using System.Reflection;
using System.Runtime.InteropServices;
using System.Security;
using System.Threading.Tasks;

namespace Csp.Common
{
    /// <summary>Represents a 3 dimensional vector.</summary>

    public class Vector3 : NativeClassWrapper, IDisposable
    {
        internal override string _safeTypeName { get; } = "csp_common_Vector3";

        #region P/Invoke
#pragma warning disable IDE1006


        [
            DllImport(
#if !UNITY_EDITOR && UNITY_IOS
            "__Internal"
#elif DEBUG && !UNITY_EDITOR_OSX && !UNITY_STANDALONE_OSX
                "ConnectedSpacesPlatform_D"
#else
                "ConnectedSpacesPlatform"
#endif
            ),
            SuppressUnmanagedCodeSecurity
        ]
        static extern float csp_common_Vector3__Get_X(IntPtr @class);

        [
            DllImport(
#if !UNITY_EDITOR && UNITY_IOS
            "__Internal"
#elif DEBUG && !UNITY_EDITOR_OSX && !UNITY_STANDALONE_OSX
                "ConnectedSpacesPlatform_D"
#else
                "ConnectedSpacesPlatform"
#endif
            ),
            SuppressUnmanagedCodeSecurity
        ]
        static extern void csp_common_Vector3__Set_X(IntPtr @class, float value);

        [
            DllImport(
#if !UNITY_EDITOR && UNITY_IOS
            "__Internal"
#elif DEBUG && !UNITY_EDITOR_OSX && !UNITY_STANDALONE_OSX
                "ConnectedSpacesPlatform_D"
#else
                "ConnectedSpacesPlatform"
#endif
            ),
            SuppressUnmanagedCodeSecurity
        ]
        static extern float csp_common_Vector3__Get_Y(IntPtr @class);

        [
            DllImport(
#if !UNITY_EDITOR && UNITY_IOS
            "__Internal"
#elif DEBUG && !UNITY_EDITOR_OSX && !UNITY_STANDALONE_OSX
                "ConnectedSpacesPlatform_D"
#else
                "ConnectedSpacesPlatform"
#endif
            ),
            SuppressUnmanagedCodeSecurity
        ]
        static extern void csp_common_Vector3__Set_Y(IntPtr @class, float value);

        [
            DllImport(
#if !UNITY_EDITOR && UNITY_IOS
            "__Internal"
#elif DEBUG && !UNITY_EDITOR_OSX && !UNITY_STANDALONE_OSX
                "ConnectedSpacesPlatform_D"
#else
                "ConnectedSpacesPlatform"
#endif
            ),
            SuppressUnmanagedCodeSecurity
        ]
        static extern float csp_common_Vector3__Get_Z(IntPtr @class);

        [
            DllImport(
#if !UNITY_EDITOR && UNITY_IOS
            "__Internal"
#elif DEBUG && !UNITY_EDITOR_OSX && !UNITY_STANDALONE_OSX
                "ConnectedSpacesPlatform_D"
#else
                "ConnectedSpacesPlatform"
#endif
            ),
            SuppressUnmanagedCodeSecurity
        ]
        static extern void csp_common_Vector3__Set_Z(IntPtr @class, float value);

        [
            DllImport(
#if !UNITY_EDITOR && UNITY_IOS
            "__Internal"
#elif DEBUG && !UNITY_EDITOR_OSX && !UNITY_STANDALONE_OSX
                "ConnectedSpacesPlatform_D"
#else
                "ConnectedSpacesPlatform"
#endif
            ),
            SuppressUnmanagedCodeSecurity
        ]
        static extern NativePointer csp_common_Vector3_Zero_Vector3RC();

        [
            DllImport(
#if !UNITY_EDITOR && UNITY_IOS
            "__Internal"
#elif DEBUG && !UNITY_EDITOR_OSX && !UNITY_STANDALONE_OSX
                "ConnectedSpacesPlatform_D"
#else
                "ConnectedSpacesPlatform"
#endif
            ),
            SuppressUnmanagedCodeSecurity
        ]
        static extern NativePointer csp_common_Vector3_One_Vector3RC();

        [
            DllImport(
#if !UNITY_EDITOR && UNITY_IOS
            "__Internal"
#elif DEBUG && !UNITY_EDITOR_OSX && !UNITY_STANDALONE_OSX
                "ConnectedSpacesPlatform_D"
#else
                "ConnectedSpacesPlatform"
#endif
            ),
            SuppressUnmanagedCodeSecurity
        ]
        static extern NativePointer csp_common_Vector3_Ctor();

        [
            DllImport(
#if !UNITY_EDITOR && UNITY_IOS
            "__Internal"
#elif DEBUG && !UNITY_EDITOR_OSX && !UNITY_STANDALONE_OSX
                "ConnectedSpacesPlatform_D"
#else
                "ConnectedSpacesPlatform"
#endif
            ),
            SuppressUnmanagedCodeSecurity
        ]
        static extern NativePointer csp_common_Vector3_Ctor_float_float_float(float X, float Y, float Z);

        [
            DllImport(
#if !UNITY_EDITOR && UNITY_IOS
            "__Internal"
#elif DEBUG && !UNITY_EDITOR_OSX && !UNITY_STANDALONE_OSX
                "ConnectedSpacesPlatform_D"
#else
                "ConnectedSpacesPlatform"
#endif
            ),
            SuppressUnmanagedCodeSecurity
        ]
        static extern void csp_common_Vector3_Dtor(IntPtr @class);

#pragma warning restore IDE1006
        #endregion

        internal Vector3(NativePointer ptr) : base(ptr) { }

        public float X
        {
            get => csp_common_Vector3__Get_X(_ptr);
            set => csp_common_Vector3__Set_X(_ptr, value);
        }

        public float Y
        {
            get => csp_common_Vector3__Get_Y(_ptr);
            set => csp_common_Vector3__Set_Y(_ptr, value);
        }

        public float Z
        {
            get => csp_common_Vector3__Get_Z(_ptr);
            set => csp_common_Vector3__Set_Z(_ptr, value);
        }

        /// <summary>Returns a Vector3 with all fields set to 0.</summary>
        /// <returns>Const vector3&</returns>


        public static Csp.Common.Vector3 Zero()
        {
            var _result = new Csp.Common.Vector3(csp_common_Vector3_Zero_Vector3RC());

            return _result;
        }

        /// <summary>Returns a Vector3 with all fields set to 1.</summary>
        /// <returns>Const vector3&</returns>


        public static Csp.Common.Vector3 One()
        {
            var _result = new Csp.Common.Vector3(csp_common_Vector3_One_Vector3RC());

            return _result;
        }

        /// <summary>Constructs a Vector3 with all fields set to 0.</summary>

        public Vector3()
        {
            var np = csp_common_Vector3_Ctor();
            _ptr = np.Pointer;
            _ownsPtr = np.OwnsOwnData;
        }

        /// <summary>Constructs a Vector3 with the given x, y, z values.</summary>
        /// <param name="X">Float</param>
        /// <param name="Y">Float</param>
        /// <param name="Z">Float</param>

        public Vector3(float X, float Y, float Z)
        {
            var np = csp_common_Vector3_Ctor_float_float_float(X, Y, Z);
            _ptr = np.Pointer;
            _ownsPtr = np.OwnsOwnData;
        }

        ~Vector3()
        {
            //RealDispose();
        }

        void RealDispose()
        {
            if (_ownsPtr && !_disposed)
            {
                csp_common_Vector3_Dtor(_ptr);
                _disposed = true;
            }

            _disposed = true;
        }

        public void Dispose()
        {
            RealDispose();
            GC.SuppressFinalize(this);
        }
    }
}

