/**
 * WARNING: DO NOT EDIT THIS FILE! IT IS A GENERATED FILE AND
 * ANY CHANGES YOU MAKE WILL BE OVERWRITTEN ON THE NEXT BUILD
 *
 * @file Version.h
 * @brief Contains the version generated for foundation.
 * @note Generated File
 */

#include "CSPFoundation.h"

/**
 * CONSTANT DEFINITIONS
 */
#define CSP_FOUNDATION_COMMIT_ID "8b94eb8d4af160ad5a400d3e39e64316ec23f0e0"
#ifdef DEBUG
#define CSP_FOUNDATION_BUILD_TYPE "DEV"
#else
#define CSP_FOUNDATION_BUILD_TYPE "REL"
#endif
#define CSP_FOUNDATION_BUILD_ID CSP_FOUNDATION_BUILD_TYPE "_231130_112928_8b94eb8d4af160ad5a400d3e39e64316ec23f0e0"

// EOF
