// WARNING: DO NOT EDIT THIS FILE! IT IS A GENERATED FILE AND
//   ANY CHANGES YOU MAKE WILL BE OVERWRITTEN ON THE NEXT BUILD

#nullable enable annotations

using System;
using System.Collections.Generic;
using System.Reflection;
using System.Runtime.InteropServices;
using System.Security;
using System.Threading.Tasks;

namespace Csp.Multiplayer
{
    /// <summary>Controls the asset and asset collection IDs used for storing external data.</summary>

    public interface IExternalResourceComponent
    {
        string GetExternalResourceAssetId();

        void SetExternalResourceAssetId(string InValue);

        string GetExternalResourceAssetCollectionId();

        void SetExternalResourceAssetCollectionId(string InValue);
    }
}

