// WARNING: DO NOT EDIT THIS FILE! IT IS A GENERATED FILE AND
//   ANY CHANGES YOU MAKE WILL BE OVERWRITTEN ON THE NEXT BUILD

#nullable enable annotations

using System;
using System.Collections.Generic;
using System.Reflection;
using System.Runtime.InteropServices;
using System.Security;
using System.Threading.Tasks;

namespace Csp.Multiplayer
{
    /// <summary>Controls the 3D rotation of the component.</summary>

    public interface IRotationComponent
    {
        Csp.Common.Vector4 GetRotation();

        void SetRotation(Csp.Common.Vector4 InValue);
    }
}

