// WARNING: DO NOT EDIT THIS FILE! IT IS A GENERATED FILE AND
//   ANY CHANGES YOU MAKE WILL BE OVERWRITTEN ON THE NEXT BUILD

#nullable enable annotations

using System;
using System.Collections.Generic;
using System.Reflection;
using System.Runtime.InteropServices;
using System.Security;
using System.Threading.Tasks;

namespace Csp.Multiplayer
{
    /// <summary>Controls access to a third party component reference.</summary>
    /// <remarks>To enable developers to author CSP powered applications using</remarks>
    /// <remarks>the native features of their platform of choice, we need to be able</remarks>
    /// <remarks>to map their platform component definition to the CSP component.</remarks>

    public interface IThirdPartyComponentRef
    {
        string GetThirdPartyComponentRef();

        void SetThirdPartyComponentRef(string InValue);
    }
}

