// WARNING: DO NOT EDIT THIS FILE! IT IS A GENERATED FILE AND
//   ANY CHANGES YOU MAKE WILL BE OVERWRITTEN ON THE NEXT BUILD

#nullable enable annotations

using System;
using System.Collections.Generic;
using System.Reflection;
using System.Runtime.InteropServices;
using System.Security;
using System.Threading.Tasks;

namespace Csp.Multiplayer
{
    /// <summary>Controls the 3D position (in world space), rotation, and scale of the component.</summary>

    public interface ITransformComponent
        : Csp.Multiplayer.IPositionComponent,
          Csp.Multiplayer.IRotationComponent,
          Csp.Multiplayer.IScaleComponent
    {
        Csp.Multiplayer.SpaceTransform GetTransform();

        void SetTransform(Csp.Multiplayer.SpaceTransform InValue);
    }
}

