// WARNING: DO NOT EDIT THIS FILE! IT IS A GENERATED FILE AND
//   ANY CHANGES YOU MAKE WILL BE OVERWRITTEN ON THE NEXT BUILD

#nullable enable annotations

using System;
using System.Collections.Generic;
using System.Reflection;
using System.Runtime.InteropServices;
using System.Security;
using System.Threading.Tasks;

namespace Csp.Multiplayer
{
    /// @ingroup FiducialMarkerSpaceComponent
    /// <summary>Data representation of a FiducialMarkerSpaceComponent.</summary>

    public class FiducialMarkerSpaceComponent
        : Csp.Multiplayer.ComponentBase,
          Csp.Multiplayer.ITransformComponent,
          Csp.Multiplayer.IVisibleComponent,
          IDisposable
    {
        internal override string _safeTypeName { get; } = "csp_multiplayer_FiducialMarkerSpaceComponent";

        #region P/Invoke
#pragma warning disable IDE1006



        [
            DllImport(
#if !UNITY_EDITOR && UNITY_IOS
            "__Internal"
#elif DEBUG && !UNITY_EDITOR_OSX && !UNITY_STANDALONE_OSX
                "ConnectedSpacesPlatform_D"
#else
                "ConnectedSpacesPlatform"
#endif
            ),
            SuppressUnmanagedCodeSecurity
        ]
        static extern NativePointer csp_multiplayer_FiducialMarkerSpaceComponent_Ctor_SpaceEntityP(IntPtr Parent);

        [
            DllImport(
#if !UNITY_EDITOR && UNITY_IOS
            "__Internal"
#elif DEBUG && !UNITY_EDITOR_OSX && !UNITY_STANDALONE_OSX
                "ConnectedSpacesPlatform_D"
#else
                "ConnectedSpacesPlatform"
#endif
            ),
            SuppressUnmanagedCodeSecurity
        ]
        static extern IntPtr csp_multiplayer_FiducialMarkerSpaceComponent_GetNameC_StringRC(IntPtr @class);

        [
            DllImport(
#if !UNITY_EDITOR && UNITY_IOS
            "__Internal"
#elif DEBUG && !UNITY_EDITOR_OSX && !UNITY_STANDALONE_OSX
                "ConnectedSpacesPlatform_D"
#else
                "ConnectedSpacesPlatform"
#endif
            ),
            SuppressUnmanagedCodeSecurity
        ]
        static extern void csp_multiplayer_FiducialMarkerSpaceComponent_SetName_void_StringRC(
            IntPtr @class,
            IntPtr Value
        );

        [
            DllImport(
#if !UNITY_EDITOR && UNITY_IOS
            "__Internal"
#elif DEBUG && !UNITY_EDITOR_OSX && !UNITY_STANDALONE_OSX
                "ConnectedSpacesPlatform_D"
#else
                "ConnectedSpacesPlatform"
#endif
            ),
            SuppressUnmanagedCodeSecurity
        ]
        static extern IntPtr csp_multiplayer_FiducialMarkerSpaceComponent_GetMarkerAssetIdC_StringRC(IntPtr @class);

        [
            DllImport(
#if !UNITY_EDITOR && UNITY_IOS
            "__Internal"
#elif DEBUG && !UNITY_EDITOR_OSX && !UNITY_STANDALONE_OSX
                "ConnectedSpacesPlatform_D"
#else
                "ConnectedSpacesPlatform"
#endif
            ),
            SuppressUnmanagedCodeSecurity
        ]
        static extern void csp_multiplayer_FiducialMarkerSpaceComponent_SetMarkerAssetId_void_StringRC(
            IntPtr @class,
            IntPtr Value
        );

        [
            DllImport(
#if !UNITY_EDITOR && UNITY_IOS
            "__Internal"
#elif DEBUG && !UNITY_EDITOR_OSX && !UNITY_STANDALONE_OSX
                "ConnectedSpacesPlatform_D"
#else
                "ConnectedSpacesPlatform"
#endif
            ),
            SuppressUnmanagedCodeSecurity
        ]
        static extern IntPtr csp_multiplayer_FiducialMarkerSpaceComponent_GetAssetCollectionIdC_StringRC(IntPtr @class);

        [
            DllImport(
#if !UNITY_EDITOR && UNITY_IOS
            "__Internal"
#elif DEBUG && !UNITY_EDITOR_OSX && !UNITY_STANDALONE_OSX
                "ConnectedSpacesPlatform_D"
#else
                "ConnectedSpacesPlatform"
#endif
            ),
            SuppressUnmanagedCodeSecurity
        ]
        static extern void csp_multiplayer_FiducialMarkerSpaceComponent_SetAssetCollectionId_void_StringRC(
            IntPtr @class,
            IntPtr Value
        );

        [
            DllImport(
#if !UNITY_EDITOR && UNITY_IOS
            "__Internal"
#elif DEBUG && !UNITY_EDITOR_OSX && !UNITY_STANDALONE_OSX
                "ConnectedSpacesPlatform_D"
#else
                "ConnectedSpacesPlatform"
#endif
            ),
            SuppressUnmanagedCodeSecurity
        ]
        static extern NativePointer csp_multiplayer_FiducialMarkerSpaceComponent_GetPositionC_Vector3RC(IntPtr @class);

        [
            DllImport(
#if !UNITY_EDITOR && UNITY_IOS
            "__Internal"
#elif DEBUG && !UNITY_EDITOR_OSX && !UNITY_STANDALONE_OSX
                "ConnectedSpacesPlatform_D"
#else
                "ConnectedSpacesPlatform"
#endif
            ),
            SuppressUnmanagedCodeSecurity
        ]
        static extern void csp_multiplayer_FiducialMarkerSpaceComponent_SetPosition_void_Vector3RC(
            IntPtr @class,
            IntPtr InValue
        );

        [
            DllImport(
#if !UNITY_EDITOR && UNITY_IOS
            "__Internal"
#elif DEBUG && !UNITY_EDITOR_OSX && !UNITY_STANDALONE_OSX
                "ConnectedSpacesPlatform_D"
#else
                "ConnectedSpacesPlatform"
#endif
            ),
            SuppressUnmanagedCodeSecurity
        ]
        static extern NativePointer csp_multiplayer_FiducialMarkerSpaceComponent_GetRotationC_Vector4RC(IntPtr @class);

        [
            DllImport(
#if !UNITY_EDITOR && UNITY_IOS
            "__Internal"
#elif DEBUG && !UNITY_EDITOR_OSX && !UNITY_STANDALONE_OSX
                "ConnectedSpacesPlatform_D"
#else
                "ConnectedSpacesPlatform"
#endif
            ),
            SuppressUnmanagedCodeSecurity
        ]
        static extern void csp_multiplayer_FiducialMarkerSpaceComponent_SetRotation_void_Vector4RC(
            IntPtr @class,
            IntPtr InValue
        );

        [
            DllImport(
#if !UNITY_EDITOR && UNITY_IOS
            "__Internal"
#elif DEBUG && !UNITY_EDITOR_OSX && !UNITY_STANDALONE_OSX
                "ConnectedSpacesPlatform_D"
#else
                "ConnectedSpacesPlatform"
#endif
            ),
            SuppressUnmanagedCodeSecurity
        ]
        static extern NativePointer csp_multiplayer_FiducialMarkerSpaceComponent_GetScaleC_Vector3RC(IntPtr @class);

        [
            DllImport(
#if !UNITY_EDITOR && UNITY_IOS
            "__Internal"
#elif DEBUG && !UNITY_EDITOR_OSX && !UNITY_STANDALONE_OSX
                "ConnectedSpacesPlatform_D"
#else
                "ConnectedSpacesPlatform"
#endif
            ),
            SuppressUnmanagedCodeSecurity
        ]
        static extern void csp_multiplayer_FiducialMarkerSpaceComponent_SetScale_void_Vector3RC(
            IntPtr @class,
            IntPtr InValue
        );

        [
            DllImport(
#if !UNITY_EDITOR && UNITY_IOS
            "__Internal"
#elif DEBUG && !UNITY_EDITOR_OSX && !UNITY_STANDALONE_OSX
                "ConnectedSpacesPlatform_D"
#else
                "ConnectedSpacesPlatform"
#endif
            ),
            SuppressUnmanagedCodeSecurity
        ]
        static extern NativePointer csp_multiplayer_FiducialMarkerSpaceComponent_GetTransformC_SpaceTransform(
            IntPtr @class
        );

        [
            DllImport(
#if !UNITY_EDITOR && UNITY_IOS
            "__Internal"
#elif DEBUG && !UNITY_EDITOR_OSX && !UNITY_STANDALONE_OSX
                "ConnectedSpacesPlatform_D"
#else
                "ConnectedSpacesPlatform"
#endif
            ),
            SuppressUnmanagedCodeSecurity
        ]
        static extern void csp_multiplayer_FiducialMarkerSpaceComponent_SetTransform_void_SpaceTransformRC(
            IntPtr @class,
            IntPtr InValue
        );

        [
            DllImport(
#if !UNITY_EDITOR && UNITY_IOS
            "__Internal"
#elif DEBUG && !UNITY_EDITOR_OSX && !UNITY_STANDALONE_OSX
                "ConnectedSpacesPlatform_D"
#else
                "ConnectedSpacesPlatform"
#endif
            ),
            SuppressUnmanagedCodeSecurity
        ]
        static extern bool csp_multiplayer_FiducialMarkerSpaceComponent_GetIsVisibleC_bool(IntPtr @class);

        [
            DllImport(
#if !UNITY_EDITOR && UNITY_IOS
            "__Internal"
#elif DEBUG && !UNITY_EDITOR_OSX && !UNITY_STANDALONE_OSX
                "ConnectedSpacesPlatform_D"
#else
                "ConnectedSpacesPlatform"
#endif
            ),
            SuppressUnmanagedCodeSecurity
        ]
        static extern void csp_multiplayer_FiducialMarkerSpaceComponent_SetIsVisible_void_bool(
            IntPtr @class,
            bool InValue
        );

        [
            DllImport(
#if !UNITY_EDITOR && UNITY_IOS
            "__Internal"
#elif DEBUG && !UNITY_EDITOR_OSX && !UNITY_STANDALONE_OSX
                "ConnectedSpacesPlatform_D"
#else
                "ConnectedSpacesPlatform"
#endif
            ),
            SuppressUnmanagedCodeSecurity
        ]
        static extern bool csp_multiplayer_FiducialMarkerSpaceComponent_GetIsARVisibleC_bool(IntPtr @class);

        [
            DllImport(
#if !UNITY_EDITOR && UNITY_IOS
            "__Internal"
#elif DEBUG && !UNITY_EDITOR_OSX && !UNITY_STANDALONE_OSX
                "ConnectedSpacesPlatform_D"
#else
                "ConnectedSpacesPlatform"
#endif
            ),
            SuppressUnmanagedCodeSecurity
        ]
        static extern void csp_multiplayer_FiducialMarkerSpaceComponent_SetIsARVisible_void_bool(
            IntPtr @class,
            bool InValue
        );

        [
            DllImport(
#if !UNITY_EDITOR && UNITY_IOS
            "__Internal"
#elif DEBUG && !UNITY_EDITOR_OSX && !UNITY_STANDALONE_OSX
                "ConnectedSpacesPlatform_D"
#else
                "ConnectedSpacesPlatform"
#endif
            ),
            SuppressUnmanagedCodeSecurity
        ]
        static extern void csp_multiplayer_FiducialMarkerSpaceComponent_Dtor(IntPtr @class);

#pragma warning restore IDE1006
        #endregion

        internal FiducialMarkerSpaceComponent(NativePointer ptr) : base(ptr) { }

        public FiducialMarkerSpaceComponent(Csp.Multiplayer.ComponentBase baseInstance)
            : base(new NativePointer(baseInstance._ptr, baseInstance._ownsPtr ? (byte)1 : (byte)0))
        {
            // Prevent previous instance from freeing underlying pointer when destroyed
            baseInstance._ownsPtr = false;
        }

        /// <summary>Constructs the fiducial marker space component, and associates it with the specified Parent space entity.</summary>
        /// <param name="Parent">The Space entity that owns this component.</param>

        public FiducialMarkerSpaceComponent(Csp.Multiplayer.SpaceEntity Parent)
        {
            var np = csp_multiplayer_FiducialMarkerSpaceComponent_Ctor_SpaceEntityP(Parent._ptr);
            _ptr = np.Pointer;
            _ownsPtr = np.OwnsOwnData;
        }

        /// <summary>Gets the name of this fiducial marker space component.</summary>
        /// <returns>The name of this fiducial marker space component.</returns>


        public string GetName()
        {
            var _result = csp_multiplayer_FiducialMarkerSpaceComponent_GetNameC_StringRC(_ptr);

            var _resultString = WrapperHelper.NativeUTF8ToString(_result);
            Global.Free(_result);

            return _resultString;
        }

        /// <summary>Sets the name of this fiducial marker space component.</summary>
        /// <param name="Value">The name of this fiducial marker space component.</param>


        public void SetName(string Value)
        {
            csp_multiplayer_FiducialMarkerSpaceComponent_SetName_void_StringRC(
                _ptr,
                WrapperHelper.StringToNativeUTF8(Value)
            );
        }

        /// <summary>Gets the ID of the image asset this image component refers to.</summary>
        /// <returns>The ID of the image asset this image component refers to.</returns>


        public string GetMarkerAssetId()
        {
            var _result = csp_multiplayer_FiducialMarkerSpaceComponent_GetMarkerAssetIdC_StringRC(_ptr);

            var _resultString = WrapperHelper.NativeUTF8ToString(_result);
            Global.Free(_result);

            return _resultString;
        }

        /// <summary>Sets the ID of the image asset this fiducial marker component refers to.</summary>
        /// <param name="Value">The ID of the image asset this fiducial marker component refers to.</param>


        public void SetMarkerAssetId(string Value)
        {
            csp_multiplayer_FiducialMarkerSpaceComponent_SetMarkerAssetId_void_StringRC(
                _ptr,
                WrapperHelper.StringToNativeUTF8(Value)
            );
        }

        /// <summary>Gets the ID of the asset collection associated with this component.</summary>
        /// <remarks>To retrieve this component's image asset, both the Asset ID and the Asset Collection ID are required.</remarks>
        /// <returns>The ID of the asset collection associated with this component.</returns>


        public string GetAssetCollectionId()
        {
            var _result = csp_multiplayer_FiducialMarkerSpaceComponent_GetAssetCollectionIdC_StringRC(_ptr);

            var _resultString = WrapperHelper.NativeUTF8ToString(_result);
            Global.Free(_result);

            return _resultString;
        }

        /// <summary>Sets the ID of the asset collection associated with this component.</summary>
        /// <remarks>To retrieve this component's image asset, both the Asset ID and the Asset Collection ID are required.</remarks>
        /// <param name="Value">The ID of the asset collection associated with this component.</param>


        public void SetAssetCollectionId(string Value)
        {
            csp_multiplayer_FiducialMarkerSpaceComponent_SetAssetCollectionId_void_StringRC(
                _ptr,
                WrapperHelper.StringToNativeUTF8(Value)
            );
        }

        /// <remarks>\addtogroup ITransformComponent</remarks>
        /// @{
        /// @copydoc IPositionComponent::GetPosition()


        public Csp.Common.Vector3 GetPosition()
        {
            var _result = new Csp.Common.Vector3(
                csp_multiplayer_FiducialMarkerSpaceComponent_GetPositionC_Vector3RC(_ptr)
            );

            return _result;
        }

        /// @copydoc IPositionComponent::SetPosition()


        public void SetPosition(Csp.Common.Vector3 InValue)
        {
            csp_multiplayer_FiducialMarkerSpaceComponent_SetPosition_void_Vector3RC(_ptr, InValue._ptr);
        }

        /// @copydoc IRotationComponent::GetRotation()


        public Csp.Common.Vector4 GetRotation()
        {
            var _result = new Csp.Common.Vector4(
                csp_multiplayer_FiducialMarkerSpaceComponent_GetRotationC_Vector4RC(_ptr)
            );

            return _result;
        }

        /// @copydoc IRotationComponent::SetRotation()


        public void SetRotation(Csp.Common.Vector4 InValue)
        {
            csp_multiplayer_FiducialMarkerSpaceComponent_SetRotation_void_Vector4RC(_ptr, InValue._ptr);
        }

        /// @copydoc IScaleComponent::GetScale()


        public Csp.Common.Vector3 GetScale()
        {
            var _result = new Csp.Common.Vector3(
                csp_multiplayer_FiducialMarkerSpaceComponent_GetScaleC_Vector3RC(_ptr)
            );

            return _result;
        }

        /// @copydoc IScaleComponent::SetScale()


        public void SetScale(Csp.Common.Vector3 InValue)
        {
            csp_multiplayer_FiducialMarkerSpaceComponent_SetScale_void_Vector3RC(_ptr, InValue._ptr);
        }

        /// @copydoc ITransformComponent::GetTransform()


        public Csp.Multiplayer.SpaceTransform GetTransform()
        {
            var _result = new Csp.Multiplayer.SpaceTransform(
                csp_multiplayer_FiducialMarkerSpaceComponent_GetTransformC_SpaceTransform(_ptr)
            );

            return _result;
        }

        /// @copydoc ITransformComonent::SetTransform()


        public void SetTransform(Csp.Multiplayer.SpaceTransform InValue)
        {
            csp_multiplayer_FiducialMarkerSpaceComponent_SetTransform_void_SpaceTransformRC(_ptr, InValue._ptr);
        }

        /// @}
        /// <remarks>\addtogroup IVisibleComponent</remarks>
        /// @{
        /// @copydoc IVisibleComponent::GetIsVisible()


        public bool GetIsVisible()
        {
            var _result = csp_multiplayer_FiducialMarkerSpaceComponent_GetIsVisibleC_bool(_ptr);

            return _result;
        }

        /// @copydoc IVisibleComponent::SetIsVisible()


        public void SetIsVisible(bool InValue)
        {
            csp_multiplayer_FiducialMarkerSpaceComponent_SetIsVisible_void_bool(_ptr, InValue);
        }

        /// @copydoc IVisibleComponent::GetIsARVisible()


        public bool GetIsARVisible()
        {
            var _result = csp_multiplayer_FiducialMarkerSpaceComponent_GetIsARVisibleC_bool(_ptr);

            return _result;
        }

        /// @copydoc IVisibleComponent::SetIsARVisible()


        public void SetIsARVisible(bool InValue)
        {
            csp_multiplayer_FiducialMarkerSpaceComponent_SetIsARVisible_void_bool(_ptr, InValue);
        }

        ~FiducialMarkerSpaceComponent()
        {
            //RealDispose();
        }

        void RealDispose()
        {
            if (_ownsPtr && !_disposed)
            {
                csp_multiplayer_FiducialMarkerSpaceComponent_Dtor(_ptr);
                _disposed = true;
            }

            _disposed = true;
        }

        new public void Dispose()
        {
            RealDispose();
            GC.SuppressFinalize(this);
        }
    }
}

