// WARNING: DO NOT EDIT THIS FILE! IT IS A GENERATED FILE AND
//   ANY CHANGES YOU MAKE WILL BE OVERWRITTEN ON THE NEXT BUILD

#nullable enable annotations

using System;
using System.Collections.Generic;
using System.Reflection;
using System.Runtime.InteropServices;
using System.Security;
using System.Threading.Tasks;

namespace Csp.Systems
{
    /// <summary>Enum for setting csp::systems::Asset third party platform type.</summary>
    /// <remarks>NONE indicates that the asset will work on any platform.</remarks>
    /// <remarks>Any other value indicates it will only work with this platform.</remarks>

    public enum EThirdPartyPlatform
    {
        NONE,
        UNREAL,
        UNITY,
    }
}

