// WARNING: DO NOT EDIT THIS FILE! IT IS A GENERATED FILE AND
//   ANY CHANGES YOU MAKE WILL BE OVERWRITTEN ON THE NEXT BUILD

#nullable enable annotations

using System;
using System.Collections.Generic;
using System.Reflection;
using System.Runtime.InteropServices;
using System.Security;
using System.Threading.Tasks;

namespace Csp.Systems
{
    /// <summary>Defines a base data source for an Asset, attributing a mime type and providing functionality for uploading the data.</summary>

    public interface AssetDataSource
    {
        string GetMimeType();

        void SetMimeType(string InMimeType);
    }
}

