# This workflow builds, installs, and optionally uploads CSP artifacts for every supported
# combination of desktop platform, build configuration, and linkage type:
#
# [Windows, MacOS, Linux]
# [Debug, Release, RelWithDebInfo]
# [Static, Shared]

name: Build Desktop

on:
  workflow_call:
    inputs:
      # The path generated for this artifact is:
      #   build/{PLATFORM_NAME_LOWERCASE}-{CONFIG_LOWERCASE}-{LINKAGE}/build/{CONFIG}
      #
      # Example:
      #   build/windows-debug-static/build/Debug
      #
      # The name generated for this artifact is:
      #   {PLATFORM_NAME_LOWERCASE}-{CONFIG_LOWERCASE}-{LINKAGE}-build
      #
      # Example:
      #   windows-debug-static-build
      upload_test_build:
        description: "If true, the build will be uploaded as an artifact. This allows us to run the csp-tests binary for testing."
        type: boolean
        required: false
        default: false

      # The path generated for this artifact is:
      #   install/{PLATFORM_NAME_LOWERCASE}/{CONFIG_LOWERCASE}-{LINKAGE}
      #
      # Example:
      #   install/windows/debug-static
      #
      # The name generated for this artifact is:
      #   {PLATFORM_NAME_LOWERCASE}-{CONFIG_LOWERCASE}-{LINKAGE}-install
      #
      # Example:
      #   windows-debug-static-install
      upload_install:
        description: "If true, the install will be uploaded as an artifact. These artifacts are used for releases."
        type: boolean
        required: false
        default: false

jobs:
  build-desktop:
    name: Build ${{ matrix.platform.name }} ${{ matrix.config.build_type }} ${{ matrix.linkage.name }}
    runs-on: ${{ matrix.platform.runner }}

    strategy:
      fail-fast: false
      matrix:
        platform:
          - name: windows
            runner: windows-2022
            host_profile: windows_ninja
            
          - name: linux
            runner: ubuntu-24.04
            host_profile: linux_gcc

          - name: macos
            runner: macos-15
            host_profile: osx_arm

        # preset_prefix - Allows us to select a cmake preset based on the build type.
        # We also use this value for build/artifact names and paths.
        config:
          - build_type: Debug
            preset_prefix: debug

          - build_type: Release
            preset_prefix: release

          - build_type: RelWithDebInfo
            preset_prefix: relwithdebinfo
        
        # preset_postfix - Allows us to select a cmake preset to build csp with tests for static builds.
        # We do this because csp tests can only be ran with static builds.
        linkage:
          - name: static
            shared: false
            preset_postfix: -tests

          - name: shared
            shared: true
            preset_postfix: ""

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          # Ensure we fetch tags so our automatic versioning script picks up the version.
          fetch-tags: true

      - name: Set up MSVC (Windows only)
        if: runner.os == 'Windows'
        uses: ilammy/msvc-dev-cmd@v1

      - name: Resolve LFS
        shell: bash
        run: |
          set -euxo pipefail

          git lfs ls-files
          git lfs pull
          git lfs checkout

      - name: Build and install
        uses: ./.github/actions/build-and-install
        with:
          host_profile: ${{ matrix.platform.host_profile }}
          build_type: ${{ matrix.config.build_type }}
          configure_preset: ${{ matrix.config.preset_prefix }}-${{ matrix.linkage.name }}${{ matrix.linkage.preset_postfix }}
          build_preset: ${{ matrix.config.preset_prefix }}-${{ matrix.linkage.name }}${{ matrix.linkage.preset_postfix }}
          output_folder: build/${{ matrix.platform.name }}-${{ matrix.config.preset_prefix }}-${{ matrix.linkage.name }}
          build_folder: build/${{ matrix.platform.name }}-${{ matrix.config.preset_prefix }}-${{ matrix.linkage.name }}/build/${{ matrix.config.build_type }}
          install_prefix: install/${{ matrix.platform.name }}/${{ matrix.config.preset_prefix }}-${{ matrix.linkage.name }}

      # Upload build artifact for testing
      # This is downloaded in a later step to run the tests.
      - name: Upload test build
        if: |
          inputs.upload_test_build &&
          matrix.config.preset_prefix == 'relwithdebinfo' &&
          matrix.linkage.name == 'static'
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.platform.name }}-${{ matrix.config.preset_prefix }}-${{ matrix.linkage.name }}-build
          path: build/${{ matrix.platform.name }}-${{ matrix.config.preset_prefix }}-${{ matrix.linkage.name }}/build/${{ matrix.config.build_type }}
          if-no-files-found: error

      - name: Upload install
        if: inputs.upload_install
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.platform.name }}-${{ matrix.config.preset_prefix }}-${{ matrix.linkage.name }}-install
          path: install/${{ matrix.platform.name }}/${{ matrix.config.preset_prefix }}-${{ matrix.linkage.name }}
          if-no-files-found: error