name: Build IOS/VisionOS

on:
  workflow_call:
    inputs:
      upload_install:
        type: boolean
        required: false
        default: false

jobs:
  ios-visionos-build:
    name: Build ${{ matrix.platform.name }} ${{ matrix.config.build_type }} ${{ matrix.linkage.name }}
    runs-on: macos-15

    strategy:
      fail-fast: false

      matrix:
        platform:
          - name: ios
            host_profile: ios_arm64

          - name: visionos
            host_profile: visionos_arm64

        config:
          - build_type: Debug
            preset_prefix: debug

          - build_type: Release
            preset_prefix: release

          - build_type: RelWithDebInfo
            preset_prefix: relwithdebinfo

        linkage:
          - name: static
            shared: false

          - name: shared
            shared: true

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          # Ensure we fetch tags so our automatic versioning script picks up the version.
          fetch-tags: true

      - name: Initialize Xcode
        shell: bash
        run: |
          set -euxo pipefail

          xcodebuild -version
          sudo xcodebuild -runFirstLaunch

      # Manually specify the OpenSSL configure target used by the Conan recipe,
      # as the OpenSSL 1.1 recipe does not fully support visionOS.
      - name: Set OpenSSL configuration for visionOS
        if: matrix.platform.name == 'visionos'
        shell: bash
        run: |
          set -euo pipefail
          echo "CONAN_OPENSSL_CONFIGURATION=ios64-xcrun" >> "$GITHUB_ENV"

      - name: Build and install
        uses: ./.github/actions/build-and-install
        with:
          host_profile: ${{ matrix.platform.host_profile }}
          build_type: ${{ matrix.config.build_type }}
          configure_preset: ${{ matrix.config.preset_prefix }}-${{ matrix.linkage.name }}
          build_preset: ${{ matrix.config.preset_prefix }}-${{ matrix.linkage.name }}
          output_folder: build/${{ matrix.platform.name }}-${{ matrix.config.preset_prefix }}-${{ matrix.linkage.name }}
          build_folder: build/${{ matrix.platform.name }}-${{ matrix.config.preset_prefix }}-${{ matrix.linkage.name }}/build/${{ matrix.config.build_type }}
          install_prefix: install/${{ matrix.platform.name }}/${{ matrix.config.preset_prefix }}-${{ matrix.linkage.name }}

      - name: Upload install
        if: inputs.create_release
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.platform.name }}-${{ matrix.config.preset_prefix }}-${{ matrix.linkage.name }}-install
          path: install/${{ matrix.platform.name }}/${{ matrix.config.preset_prefix }}-${{ matrix.linkage.name }}
          if-no-files-found: error
