name: Run Node tests
on: workflow_dispatch
jobs:
  run_tests:
    if: github.repository == 'magnopus-opensource/connected-spaces-platform'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: UnitTesting
    steps:
      - name: Setup Python
        uses: actions/setup-python@v3.1.4
        with:
          python-version: 3.10.5
          architecture: x64
      - name: Install Python requirements
        run: pip install -r ../requirements.txt
      - name: Setup premake
        uses: abel0b/setup-premake@v2.2
        with:
          version: 5.0.0-beta2
      - name: Setup Emscripten toolchain
        uses: mymindstorm/setup-emsdk@v12
        with:
          version: latest
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.1.x
      - name: Generate dummy library
        run: python scripts/GenerateExports.py
      - name: Generate unit tests
        run: python scripts/GenerateTests.py
      - name: Generate makefile
        run: premake5 gmake2 --generate_wasm
      - name: Build WASM binary
        run: emmake make -j 8 config=debug_wasm
      - name: Run Node tests
        run: python tests/RunNodeTests.py
