name: 'Check Branch'

on:
  pull_request:

jobs:
  check_branch:
    runs-on: ubuntu-latest
    steps:
      - name: Check branch
        if: github.base_ref == 'main' && !contains(github.head_ref, 'staging/')
        run: |
          echo "ERROR: You can only merge to main from branches matching `staging/*`."
          exit 1