# This workflow performs the following actions:
#  - Builds csp for all desktop platforms
#  - Builds csp for wasm
#  - Builds csp for android
#  - Builds csp for iOS and visionOS
#  - Builds csp using legacy wasm wrapper
#  - Runs csp local tests on Linux

name: PR Checks

on:
  pull_request:
    branches:
      - main

jobs:
  desktop:
    uses: ./.github/workflows/desktop-build.yml
    with:
      upload_test_build: true
      upload_install: false
    
  wasm:
    uses: ./.github/workflows/wasm-build.yml
    with:
      upload_install: false
  
  android:
    uses: ./.github/workflows/android-build.yml
    with:
      upload_install: false

  ios-visionos:
    uses: ./.github/workflows/ios-visionos-build.yml
    with:
      upload_install: false

  legacy-wasm:
    uses: ./.github/workflows/legacy-wasm-build.yml
    secrets: inherit
    with:
      upload_package: false
      run_tests: true

  local-mcs-tests:
    uses: ./.github/workflows/local-mcs-tests-run.yml
    secrets: inherit
    needs: desktop