name: PR Checks

# This workflow performs the following actions:
#  - Builds all desktop platforms
#  - Uploads the install tree as a workflow artifact
#  - Builds csp as emscripten static lib
#  - Builds csp for android
#  - Builds csp for iOS and visionOS
#  - Runs csp locsl tests on Linux

on:
  pull_request:
    branches:
      - main

jobs:
  desktop:
    uses: ./.github/workflows/desktop-build.yml
    with:
      upload_test_build: true
      upload_install: false
    
  wasm:
    uses: ./.github/workflows/wasm-build.yml
    with:
      upload_install: false
  
  android:
    uses: ./.github/workflows/android-build.yml
    with:
      upload_install: false

      - name: Setup emsdk
        uses: emscripten-core/setup-emsdk@v15
        with:
          version: ${{ env.EMSDK_VERSION }}
          actions-cache-folder: 'emsdk-cache'

      - name: Build Emscripten
        uses: ./.github/actions/build-legacy-emscripten
        with:
          build_type: ${{ matrix.config.build_type }}
          configure_preset: ${{ matrix.config.preset_prefix }}-static
          build_preset: ${{ matrix.config.preset_prefix }}-static
          output_folder: build/emscripten-${{ matrix.config.preset_prefix }}
          build_folder: build/emscripten-${{ matrix.config.preset_prefix }}/build/${{ matrix.config.build_type }}

      - name: Run Tests
        if: matrix.config.build_type == 'Debug'
        env:
          MCS_X_WAF_BYPASS: ${{ secrets.MCS_BYPASS }}
        shell: bash
        run: |
          cd WasmTesting
          ./run-csp-wasm-tests.cmd